version=pmwiki-2.2.97 ordered=1 urlencoded=1
agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
author=PrettyNPink
charset=ISO-8859-1
csum=
ctime=1517384879
host=172.114.41.103
name=Players.Trigger
rev=1
targets=
text=(:div %25width=970px style='color:white;background-repeat:no-repeat;background-attachment:fixed;background-color:black;background-position:top center;background-image:url([=https://i.imgur.com/vyvJBPU.jpg=]); background-size:80%25; padding:25px;' width=25%25:)%0a%0a%25center%25https://i.imgur.com/l9gGxDu.jpg%0a
time=1517384879
author:1517384879=PrettyNPink
diff:1517384879:1517384879:=1,3d0%0a%3c (:div %25width=970px style='color:white;background-repeat:no-repeat;background-attachment:fixed;background-color:black;background-position:top center;background-image:url([=https://i.imgur.com/vyvJBPU.jpg=]); background-size:80%25; padding:25px;' width=25%25:)%0a%3c %0a%3c %25center%25https://i.imgur.com/l9gGxDu.jpg%0a
host:1517384879=172.114.41.103
