version=pmwiki-2.2.97 ordered=1 urlencoded=1
agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
author=PrettyNPink
charset=ISO-8859-1
csum=
ctime=1517384879
host=172.114.41.103
name=Players.Trigger
rev=3
targets=Players.NoahMasterRyans,Players.WaverlyDaisyRoseway,Players.MollyDiceDavenport,Players.AdamLughWoodburn,Players.MichaelSmithCarpenter,Players.DustinMythWard,Players.ElizabethPhoebeWard
text=(:div %25width=970px style='color:white;background-repeat:no-repeat;background-attachment:fixed;background-color:black;background-position:top center;background-image:url([=https://i.imgur.com/vyvJBPU.jpg=]); background-size:80%25; padding:25px;' width=25%25:)%0a%0a%25center%25https://i.imgur.com/l9gGxDu.jpg%0a%0a%0a%25center%25[[NoahMasterRyans | https://i.imgur.com/i4fXnpF.jpg]]%0a%25center%25[[WaverlyDaisyRoseway | https://i.imgur.com/zUucHVo.jpg]]%0a%25center%25[[MollyDiceDavenport | https://i.imgur.com/ICGQXso.jpg]]%0a%25center%25[[AdamLughWoodburn | https://i.imgur.com/e6ASOKh.jpg]]%0a%25center%25[[MichaelSmithCarpenter | https://i.imgur.com/BiIkqQ7.jpg]]%0a%25center%25[[DustinMythWard | https://i.imgur.com/2HN0XpF.jpg]]%0a%25center%25[[ElizabethPhoebeWard | https://i.imgur.com/JRLi1bh.jpg]]
time=1517385685
author:1517385685=PrettyNPink
diff:1517385685:1517385643:=7c7%0a%3c %25center%25[[WaverlyDaisyRoseway | https://i.imgur.com/zUucHVo.jpg]]%0a---%0a> %25center%25[[WaverlyDaisyAdams | https://i.imgur.com/zUucHVo.jpg]]%0a
host:1517385685=172.114.41.103
author:1517385643=PrettyNPink
diff:1517385643:1517384879:=4,12d3%0a%3c %0a%3c %0a%3c %25center%25[[NoahMasterRyans | https://i.imgur.com/i4fXnpF.jpg]]%0a%3c %25center%25[[WaverlyDaisyAdams | https://i.imgur.com/zUucHVo.jpg]]%0a%3c %25center%25[[MollyDiceDavenport | https://i.imgur.com/ICGQXso.jpg]]%0a%3c %25center%25[[AdamLughWoodburn | https://i.imgur.com/e6ASOKh.jpg]]%0a%3c %25center%25[[MichaelSmithCarpenter | https://i.imgur.com/BiIkqQ7.jpg]]%0a%3c %25center%25[[DustinMythWard | https://i.imgur.com/2HN0XpF.jpg]]%0a%3c %25center%25[[ElizabethPhoebeWard | https://i.imgur.com/JRLi1bh.jpg]]%0a\ No newline at end of file%0a
host:1517385643=172.114.41.103
author:1517384879=PrettyNPink
diff:1517384879:1517384879:=1,3d0%0a%3c (:div %25width=970px style='color:white;background-repeat:no-repeat;background-attachment:fixed;background-color:black;background-position:top center;background-image:url([=https://i.imgur.com/vyvJBPU.jpg=]); background-size:80%25; padding:25px;' width=25%25:)%0a%3c %0a%3c %25center%25https://i.imgur.com/l9gGxDu.jpg%0a
host:1517384879=172.114.41.103
